### ISSUE TITLE
Support NPM 3.*

### ISSUE THREAD

**Issue by nicekiwi** [ammeep/electron-accelerator#26]
running on npm 3 gives `npm ERR! Cannot find module './lib'` when running scripts/bootstrap on mac.

**Comment by ammeep** [comment]
Hi @nicekiwi This is next up!

**Comment by nicekiwi** [comment]
![hzaj4hn](https://cloud.githubusercontent.com/assets/738975/11463434/378eb318-9786-11e5-8ef1-50294bb320c4.png)

**Comment by martin308** [comment]
seems to work fine with NPM v3.3.4 for me at least

**Comment by plrthink** [comment]
yeah, also npm v3.3.9

**Comment by ammeep** [comment]
@nicekiwi if you could give the latest (0.0.5) a whirl that would be super helpful :bow:
